* Running

- "cargo run" will run "mcap"
- tests:
  - cargo test
  - cargo bench
  - cargo llvm-cov --html

For memory use, there is a Nix flake for setup too.
  - nix run '.#memuse'
  - this should output something like:

        Max heap usage of 60087 bytes for encoding 311615 bytes
        Max heap used is 19 percent of the input file.

(On Debian, you can get the required Nix setup via "apt install
nix-setup-systemd" followed by adding your user to "nix-users")

* Glossary

**Read Cap**: a short base64-encoded string, can be used to decrypt Data

**Data**: metadata + ciphertext that can unlocked with a "Read Cap"

**Verify Cap**: a short base64-encoded string that can verify the validity of Data (but not decrypt it)

A "Read Cap" (or "Verify Cap") "corresponds to" a given Data if it may decrypt (or only verify) it.

**An Identifier**: a random string derived from a "Read Cap" (or "Verify Cap") that uniquely identifies it (e.g. within a Catalog)

**Catalog**: a collection of Data organized by "an Identifier" (at some root directory or URL, for example)


* Catalog next steps

** hosting a Catalog

- can do it in github (we have one right now in this repo!)
- filesystem one just has the mcap files in it (and metadata could be
  gotten on-demand easily)
- a "web" one wants a more structured API -- we _can_ do it with
  offsets etc but then you've burned together the network API and the
  serialization format
- something like:
  "<root>/mcap/<locator>/metadata"
  "<root>/mcap/<locator>/blocks"
- versioning? (do we burn in version-0 ^ somewhere so we can
  double-check the "mcap" and "0u32" value at the front of the files?
- could stick a "smart" Web server in front of any catalogs and it can
  dynamically map the above API (reading the files as required)
- could run a command locally, "compiling" to static output that matches the above?
  (note: flattens the on-disc format to one directory!)
- 'mcap publish <catalog-path> <output-path>'

REST API as implemented by the output of "mcap publish" is:

- <root> (some hard-to-guess or otherwise "secrit" URL? if you care about disclosing how many + size of publish?)
  - /magic-cap-catalog: JSON with keys:
    - "version": 0
  - /<location-id>
    - /metadata: the MsgPack-encoded metadata
    - /ciphertext: all the blocks of ciphertext, in order

-> so, could make a RemoteHttpCatalog type or similar, to access one of these
   double-check root/magic-cap-catalog == {"version": 0}
   turn ImmutableIdentifier -> metadata + ciphertext

   (do we really want a "push consumer" API so instead of asking
   "get_block(12)" from the above .. which would basically have to do
   range-requests for each block?? .. we could instead just say
   "download it all" and get blocks as they come?

   but wait! can't we do that already?
   ...okay lets write "mcap decrypt --url https://meejah.ca/mcap/..."

** network caps

- thinking a little about "network caps"
- right now we can do something like this:

  cargo run -- decrypt --catalog ./kitten-catalog mcap0rY2fm_lVL33W9-DfIUH01EzAT7fUQ3c5lZEGuZW-WyppXBR8ws_mMNghZAg7wxIUB > kitten.jpeg

- generalizing a bit, "--catalog <network-read-cap>" could generalize
  to any sort of "place to get ciphertext" (github, S3, ...)
- ...and for "mcap encrypt" it needs "--catalog <network-write-cap>"

- What do those "network caps" look like?
- Next step: a "network-read-cap" for GitHub (_and_ "local file store")
  - _could_ it just be as simple as a URI for now?
    file:///home/meejah/src/magic_cap/kitten-catalog
    https://github.com

- Write-caps get harder, because you need permissions or authority or credentials "or something".
  - git@github.com:...... (not great, because "ambient" perms, from your SSH schmoo)
  - s3:.....? (insert screaming)

- So in like general we probably want something both more structured and more opaque
  - net0wfm_lVL33W9-DfIUH01EzAT7fUQ3c5lZEGuZW-WyppXBR8ws_
    (where we can encode whatever binary or ascii in there as required)

- There are some advantages to "ambient" collection-caps, like the
  filesystem one: you don't "leak" much information (and zero actual
  credentials) so you can share it with others more easily -- and if
  they have (or are granted) the right permissions, then it'll work

- Similar for "a github read-cap": might not work at first, but if I
  "invite" you to the repo, all of a sudden it does (and it doesn't
  burn in an SSH private key or something)

- might want a top-level / human-readable way to distinguish "ambient
  authority" network caps from "embedded authority" network caps
  (e.g. an "embedded" file-system cap might have "username +
  password + path", obviously something you don't want to share .. and
  probably not something we want to implement!)
