* Running

- "cargo run" will run "mcap"
- tests:
  - cargo test
  - cargo bench
  - cargo llvm-cov --html

- linting:
  - run these on any commit, "main" should always pass these
  - cargo fmt
  - cargo clippy

For memory use, there is a Nix flake for setup too.
  - nix run '.#memuse'
  - this should output something like:

        Max heap usage of 60087 bytes for encoding 311615 bytes
        Max heap used is 19 percent of the input file.

(On Debian, you can get the required Nix setup via "apt install
nix-setup-systemd" followed by adding your user to "nix-users")

* Tools

**encode-kittens.py**: this creates the example Catalog using the demo kitten pictures.
This takes all the pictures in ``data/kittens`` and encodes them to the Catalog rooted at ``data/root``.

**decode_cap.py**: read and verify the metadata (and encrypted metadata) when given a Read Cap and a Data file.
For example:

#+begin_src sh
python decode_cap.py kitten.mcap mcap0r3LsgJf1LYZtRc_BGOzhx8j_FVDmFROmoBhDHGNTfXq8EAnU9NkykdwXfOg6VdQ7v
#+end_src

#+RESULTS:
: Metadata hash matches Capability String
:   size: 306199 bytes (75 x 4096-byte blocks)
:   root: 797f7bf16746b21284ad603a9561eaf673c86586821c538c03f86e5f328c3316
:   encrypted metadata:
:     mime-type: text/plain
:     suggested-filename: /etc/passwd


* Making a Release

- ensure on main (via "jj", perhaps a "jj new")
- update versions
  - magic_cap/Cargo.toml
  - mcap/Cargo.toml
  - ./Cargo.toml (dependency ... can we automate?)
- test
  - cargo publish --workspace --all-features --dry-run

* Glossary

**Read Cap**: a short base64-encoded string, can be used to decrypt Data

**Data**: metadata + ciphertext that can unlocked with a "Read Cap"

**Verify Cap**: a short base64-encoded string that can verify the validity of Data (but not decrypt it)

A "Read Cap" (or "Verify Cap") "corresponds to" a given Data if it may decrypt (or only verify) it.

**An Locator**: a random string derived from a "Read Cap" (or "Verify Cap") that uniquely identifies it (e.g. within a Catalog)

**Catalog**: a collection of Data organized by "a Locator" (at some root directory or URL, for example)


* Catalogs

Using a literary metaphore we have two different names for ways to bundle many things together: Catalog and Anthology.

A "Catalog" is like a "card catalog" in libraries: you can look thinkgs up.
In our case, we can look up Data + Metadata via a "Locator" (gotten from a Read Cap or Verify Vap).

These Locators are a long lower-case hex string, like ``2bb197645f37b4dba534daff46855b0eb2ab7a9f4e0acba7ec832aa107e6e8de``

On-disk or filesystem Catalogs look something like a git objects directory, with a series of two-character directories breaking things up (so the above Locator is put in ``<root>/2b/2b197...8de``.

For a ReST-like Web API, we define URLs like this: ``https://example.com/.../<locator>/metadata`` and ``https://example.com/.../<locator>/ciphertext`` for reading the metadata and ciphertext (respectively) for the given Locator.

The elipsis (``...``) is up to the deployer to define; this could be an impossible-to-guess string (with directory-listing turned off) or similar.
It could have further authorization or authentication schemes in front of it.
However it is deployed, the server shouldn't allow enumeration of all the Locators (as this leaks the number and size of stored Capabilities).
That said, even a full-public Catalog could have use-cases.

(We're excited to hear about *your* use-cases!)

** hosting a Catalog

REST API as implemented by the output of "mcap publish" is:

- <root> (some hard-to-guess or otherwise "secrit" URL? if you care about disclosing how many + size of publish?)
  - /magic-cap-catalog: JSON with keys:
    - "version": 0
  - /<location-id>
    - /metadata: the MsgPack-encoded metadata
    - /ciphertext: all the blocks of ciphertext, in order

In Rust, we have ``magic_cap::catalog::ImmutableWebCatalog`` which knows how to access the above REST API (using ``reqwest``).

Using the CLI: ``mcap decrypt --catalog-url https://meejah.ca/media/mcap/secret-name/ mcap0rY2fm_lVL33W9-DfIUH01EzAT7fUQ3c5lZEGuZW-WyppXBR8ws_mMNghZAg7wxIUB > bruennhilde.jpeg``

You can create a ready-to-static-host version of a catalog using ``mcap publish``.
So if the above on-disk catalog was in ``kittens-catalog/`` you could turn it into something that can be scp'd or rsync'd to a remote server and statically-hosted by any Web server (turn off directory listings!).

``mcap publish kittens-catalog/ /tmp/published``

** network caps

- thinking a little about "network caps"
- right now we can do something like this:

  cargo run -- decrypt --catalog ./kitten-catalog mcap0rY2fm_lVL33W9-DfIUH01EzAT7fUQ3c5lZEGuZW-WyppXBR8ws_mMNghZAg7wxIUB > kitten.jpeg

- generalizing a bit, "--catalog <network-read-cap>" could generalize
  to any sort of "place to get ciphertext" (github, S3, ...)
- ...and for "mcap encrypt" it needs "--catalog <network-write-cap>"

- What do those "network caps" look like?
- Next step: a "network-read-cap" for GitHub (_and_ "local file store")
  - _could_ it just be as simple as a URI for now?
    file:///home/meejah/src/magic_cap/kitten-catalog
    https://github.com

- Write-caps get harder, because you need permissions or authority or credentials "or something".
  - git@github.com:...... (not great, because "ambient" perms, from your SSH schmoo)
  - s3:.....? (insert screaming)

- So in like general we probably want something both more structured and more opaque
  - net0wfm_lVL33W9-DfIUH01EzAT7fUQ3c5lZEGuZW-WyppXBR8ws_
    (where we can encode whatever binary or ascii in there as required)

- There are some advantages to "ambient" collection-caps, like the
  filesystem one: you don't "leak" much information (and zero actual
  credentials) so you can share it with others more easily -- and if
  they have (or are granted) the right permissions, then it'll work

- Similar for "a github read-cap": might not work at first, but if I
  "invite" you to the repo, all of a sudden it does (and it doesn't
  burn in an SSH private key or something)

- might want a top-level / human-readable way to distinguish "ambient
  authority" network caps from "embedded authority" network caps
  (e.g. an "embedded" file-system cap might have "username +
  password + path", obviously something you don't want to share .. and
  probably not something we want to implement!)
