* Running

- "cargo run" will run "mcap"
- tests:
  - cargo test
  - cargo bench
  - cargo llvm-cov --html

For memory use, there is a Nix flake for setup too.
  - nix run '.#memuse'
  - this should output something like:

        Max heap usage of 60087 bytes for encoding 311615 bytes
        Max heap used is 19 percent of the input file.

(On Debian, you can get the required Nix setup via "apt install
nix-setup-systemd" followed by adding your user to "nix-users")

* Glossary

**Read Cap**: a short base64-encoded string, can be used to decrypt Data

**Data**: metadata + ciphertext that can unlocked with a "Read Cap"

**Verify Cap**: a short base64-encoded string that can verify the validity of Data (but not decrypt it)

A "Read Cap" (or "Verify Cap") "corresponds to" a given Data if it may decrypt (or only verify) it.

**An Identifier**: a random string derived from a "Read Cap" (or "Verify Cap") that uniquely identifies it (e.g. within a Catalog)

**Catalog**: a collection of Data organized by "an Identifier" (at some root directory or URL, for example)


* Catalog next steps

- thinking a little about "network caps"
- right now we can do something like this:

  cargo run -- decrypt --catalog ./kitten-catalog mcap0rY2fm_lVL33W9-DfIUH01EzAT7fUQ3c5lZEGuZW-WyppXBR8ws_mMNghZAg7wxIUB > kitten.jpeg

- generalizing a bit, "--catalog <network-read-cap>" could generalize
  to any sort of "place to get ciphertext" (github, S3, ...)
- ...and for "mcap encrypt" it needs "--catalog <network-write-cap>"

- What do those "network caps" look like?
- Next step: a "network-read-cap" for GitHub (_and_ "local file store")
  - _could_ it just be as simple as a URI for now?
    file:///home/meejah/src/magic_cap/kitten-catalog
    https://github.com

- Write-caps get harder, because you need permissions or authority or credentials "or something".
  - git@github.com:...... (not great, because "ambient" perms, from your SSH schmoo)
  - s3:.....? (insert screaming)

- So in like general we probably want something both more structured and more opaque
  - net0wfm_lVL33W9-DfIUH01EzAT7fUQ3c5lZEGuZW-WyppXBR8ws_
    (where we can encode whatever binary or ascii in there as required)

- There are some advantages to "ambient" collection-caps, like the
  filesystem one: you don't "leak" much information (and zero actual
  credentials) so you can share it with others more easily -- and if
  they have (or are granted) the right permissions, then it'll work

- Similar for "a github read-cap": might not work at first, but if I
  "invite" you to the repo, all of a sudden it does (and it doesn't
  burn in an SSH private key or something)

- might want a top-level / human-readable way to distinguish "ambient
  authority" network caps from "embedded authority" network caps
  (e.g. an "embedded" file-system cap might have "username +
  password + path", obviously something you don't want to share .. and
  probably not something we want to implement!)
