[package]
name = "magic_cap"
version = "0.1.0"
edition = "2024"
authors = [
    "meejah <meejah@meejah.ca>",
    "shapr <shae@ScannedInAvian.com>",
]
license = "AGPL-3.0-or-later"
description = "Magic Cap is a user-friendly tool for encrypted files."
documentation = "https://docs.rs/crates/magic_cap"
homepage = "https://github.com/magic-cap"
repository = "https://github.com/magic-cap/magic-cap"
readme = "../README.org"
keywords = ["crypto", "cryptography", "cli", "security"]
categories = ["cryptography", "command-line-utilities", "data-structures", "encoding", "security"]
publish = true  # when flipping this, ensure GitHub repo is public (add homepage etc too if avail)

[lints.rust]
unsafe_code = "forbid"

[dependencies]
aes = { workspace = true }
cipher = { workspace = true }
ctr = { workspace = true }
data-encoding = { workspace = true }
getrandom = { workspace = true, features = ["std"] }
rmp-serde = { workspace = true }
rs_merkle = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }
thiserror = { workspace = true }
tempfile = { workspace = true }
reqwest = { workspace = true, features = ["blocking"] }
url = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
hkdf = { workspace = true  }
include-doc = { workspace = true }


[dev-dependencies]
proptest = { workspace = true }
tempfile = { workspace = true }
# vulns below
# criterion = { workspace = true, features = ["html_reports"] }
# cargo-llvm-cov = { workspace = true }

[package.metadata.cargo-udeps.ignore]
normal = ["proptest"]

[profile.release]
opt-level = 3

[[bench]]
name = "encode"
harness = false
