[package]
name = "magic_cap_cli"
version = "0.0.1"
edition = "2024"
authors = [
    "meejah <meejah@meejah.ca>",
    "shapr <shae@ScannedInAvian.com>",
]
license = "AGPL-3.0-or-later"
description = "Magic Cap is a user-friendly tool for encrypted files."
##documentation = ""
homepage = "https://github.com/magic-cap"
repository = "https://github.com/magic-cap/magic-cap"
readme = "../README.org"
keywords = ["crypto", "cryptography", "cli", "security"]
categories = ["cryptography", "command-line-utilities", "data-structures", "encoding", "security"]
publish = true  # when flipping this, ensure GitHub repo is public (add homepage etc too if avail)

[[bin]]
name = "mcap"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
magic_cap = { path = "../magic_cap", version = "0.0.1" }
reqwest = { version = "0.13.3", features = ["blocking"] }
tempfile = "3.24.0"
url = "2.5.8"

[dev-dependencies]
proptest = "1.9.0"
tempfile = "3.24.0"
